kind: pipeline
type: docker
name: filebrowser-deploy

steps:
  - name: deploy
    image: docker:24-cli
    commands:
      - apk add --no-cache docker-compose
      - docker-compose down || true
      - docker network rm src_filebrowser || true
      - docker-compose pull
      - docker-compose up -d
    when:
      branch:
        - main
      event:
        - push
