kind: pipeline
type: docker
name: seafile-deploy

steps:
  - name: deploy
    image: docker:24-cli
    environment:
      SEAFILE_MYSQL_ROOT_PASSWORD:
        from_secret: SEAFILE_MYSQL_ROOT_PASSWORD
      SEAFILE_ADMIN_EMAIL:
        from_secret: SEAFILE_ADMIN_EMAIL
      SEAFILE_ADMIN_PASSWORD:
        from_secret: SEAFILE_ADMIN_PASSWORD
      SEAFILE_SERVER_HOSTNAME:
        from_secret: SEAFILE_SERVER_HOSTNAME
    commands:
      - apk add --no-cache docker-compose
      - docker network create seafile-network || true
      - docker-compose down || true
      - docker-compose pull
      - docker-compose up -d
    when:
      branch:
        - main
      event:
        - push
