networks:
  traefik:
    external: true
  seafile-network:
    external: true

services:
  seafile-mysql:
    image: mariadb:10.11
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SEAFILE_MYSQL_ROOT_PASSWORD}
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - /mnt/nas-direct/seafile-mysql:/var/lib/mysql
    networks:
      - seafile-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  memcached:
    image: memcached:1.6-alpine
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 256M

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    volumes:
      - /mnt/nas-direct/seafile-data:/shared
    environment:
      - DB_HOST=seafile-mysql
      - DB_ROOT_PASSWD=${SEAFILE_MYSQL_ROOT_PASSWORD}
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}
      - SEAFILE_SERVER_HOSTNAME=${SEAFILE_SERVER_HOSTNAME}
      - SEAFILE_SERVER_PROTOCOL=https
      - SEAFILE_SERVER_LETSENCRYPT=false
      - TIME_ZONE=America/New_York
    depends_on:
      - seafile-mysql
      - memcached
    networks:
      - traefik
      - seafile-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.seafile.rule=Host(`files.bobparsons.dev`)"
      - "traefik.http.routers.seafile.entrypoints=http,https"
      - "traefik.http.routers.seafile.tls.certresolver=letsencrypt"
      - "traefik.http.services.seafile.loadbalancer.server.port=80"
      - "traefik.http.routers.seafile.middlewares=security-headers,seafile-timeout"
      - "traefik.http.middlewares.seafile-timeout.timeout.request=3600s"


