# Remove the version line (it's obsolete)
networks:
  traefik:
    external: true
  seafile-internal:
    driver: bridge

volumes:
  seafile-db:
  seafile-data:

services:
  seafile-mysql:
    image: mariadb:10.11
    container_name: seafile-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - seafile-db:/var/lib/mysql
    networks:
      - seafile-internal
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s # Give MySQL time to initialize

  seafile-memcached:
    image: memcached:1.6-alpine
    container_name: seafile-memcached
    restart: unless-stopped
    entrypoint: memcached -m 256
    networks:
      - seafile-internal

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    restart: unless-stopped
    depends_on:
      seafile-mysql:
        condition: service_healthy
    volumes:
      - seafile-data:/shared
    environment:
      - DB_HOST=seafile-mysql
      - DB_ROOT_PASSWD=${DB_PASSWORD}
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}
      - SEAFILE_SERVER_HOSTNAME=files.waugze.com
      - SEAFILE_SERVER_PROTOCOL=https
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SERVICE_URL=https://files.waugze.com
      - FILE_SERVER_ROOT=https://files.waugze.com/seafhttp
      - FORCE_HTTPS_IN_CONF=true
      - TIME_ZONE=${TZ:-America/Chicago}
    networks:
      - traefik
      - seafile-internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.seafile.rule=Host(`files.waugze.com`)"
      - "traefik.http.routers.seafile.entrypoints=http,https"
      - "traefik.http.routers.seafile.tls.certresolver=letsencrypt"
      - "traefik.http.services.seafile.loadbalancer.server.port=80"
      - "traefik.http.routers.seafile.middlewares=seafile-headers@docker"
      # Add essential headers middleware
      - "traefik.http.middlewares.seafile-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.seafile-headers.headers.customrequestheaders.X-Forwarded-Port=443"
      - "traefik.http.middlewares.seafile-headers.headers.customrequestheaders.X-Forwarded-Host=files.waugze.com"
