version: "3.8"

networks:
  traefik:
    external: true
  seafile-internal:
    driver: bridge

volumes:
  seafile-db:
  seafile-data:

services:
  # MariaDB Database
  seafile-mysql:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - seafile-db:/var/lib/mysql
    networks:
      - seafile-internal
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 20s
      timeout: 5s
      retries: 10

  # Memcached
  seafile-memcached:
    image: memcached:1.6
    restart: unless-stopped
    entrypoint: memcached -m 256
    networks:
      - seafile-internal

  # Seafile Server
  seafile:
    image: seafileltd/seafile-mc:latest
    restart: unless-stopped
    depends_on:
      seafile-mysql:
        condition: service_healthy
    networks:
      - traefik
      - seafile-internal
    volumes:
      - seafile-data:/shared
    environment:
      - DB_HOST=seafile-mysql
      - DB_ROOT_PASSWD=${DB_PASSWORD}
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=files.waugze.com
      - TIME_ZONE=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.seafile.loadbalancer.server.port=80"
      - "traefik.http.routers.seafile.rule=Host(`files.waugze.com`)"
      - "traefik.http.routers.seafile.entrypoints=websecure"
      - "traefik.http.routers.seafile.tls.certresolver=letsencrypt"
      - "traefik.http.routers.seafile.middlewares=seafile-headers@docker,seafile-buffering@docker"
      - "traefik.http.middlewares.seafile-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.seafile-headers.headers.customrequestheaders.X-Forwarded-Port=443"
      - "traefik.http.middlewares.seafile-headers.headers.framedeny=true"
      - "traefik.http.middlewares.seafile-headers.headers.contenttypenosniff=true"
      - "traefik.http.middlewares.seafile-headers.headers.stsseconds=31536000"
      - "traefik.http.middlewares.seafile-buffering.buffering.maxRequestBodyBytes=10737418240"
      - "traefik.http.middlewares.seafile-buffering.buffering.memRequestBodyBytes=1073741824"
