networks:
  traefik:
    external: true
  seafile-network:
    external: true

services:
  seafile-mysql:
    image: mariadb:10.11
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SEAFILE_MYSQL_ROOT_PASSWORD}
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - /home/server/files/seafile-mysql:/var/lib/mysql
    networks:
      - seafile-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    # deploy:
    #   resources:
    #     limits:
    #       memory: 4G
    #     reservations:
    #       memory: 2G

  memcached:
    image: memcached:1.6-alpine
    container_name: seafile-memcached
    entrypoint: memcached -m 1024
    networks:
      - seafile-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 30s
      timeout: 10s
      retries: 3
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1.5G
    #     reservations:
    #       memory: 1G

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    user: "0:0" # Run as root to avoid ownership issues
    volumes:
      - /home/server/files/seafile:/shared
      # Remove the second mount initially, add after setup
      # - /mnt/nas-direct/seafile-library:/shared/seafile/seafile-data
    environment:
      - DB_HOST=seafile-mysql
      - DB_ROOT_PASSWD=${SEAFILE_MYSQL_ROOT_PASSWORD}
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}
      - SEAFILE_SERVER_HOSTNAME=${SEAFILE_SERVER_HOSTNAME}
      - SEAFILE_SERVER_PROTOCOL=https
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SERVICE_URL=https://files.waugze.com
      - FILE_SERVER_ROOT=https://files.waugze.com/seafhttp
      - ALLOWED_HOSTS=files.waugze.com
      - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
      - USE_X_FORWARDED_HOST=true
      - USE_X_FORWARDED_PORT=true
      - CSRF_TRUSTED_ORIGINS=https://files.waugze.com
      - FORCE_HTTPS_IN_CONF=true
      - TIME_ZONE=America/Chicago
    depends_on:
      - seafile-mysql
      - memcached
    networks:
      - traefik
      - seafile-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
    # deploy:
    #   resources:
    #     limits:
    #       memory: 8G
    #     reservations:
    #       memory: 4G
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.seafile.rule=Host(`files.waugze.com`)"
      - "traefik.http.routers.seafile.entrypoints=http,https"
      - "traefik.http.routers.seafile.tls.certresolver=letsencrypt"
      - "traefik.http.services.seafile.loadbalancer.server.port=80"
      # - "traefik.http.routers.seafile.middlewares=security-headers,seafile-timeout"
      # - "traefik.http.middlewares.seafile-timeout.timeout.request=3600s"
